TEncSearch: Fix compile error due to char array subscript.
Sample compile errors in Linux64/GCC4.8.1:

$HEVC/source/Lib/TLibEncoder/TEncSearch.cpp:2134:75: error: array subscript has type ?char? [-Werror=char-subscripts]
     x265::pixelcmp sa8d = x265::primitives.sa8d[g_aucConvertToBit[uiWidth]];
                                                                           ^
$HEVC/source/Lib/TLibEncoder/TEncSearch.cpp: In member function ?Void TEncSearch::estIntraPredQT(TComDataCU*, TComYuv*, TComYuv*, TShortYUV*, TComYuv*, UInt&, Bool)?:
$HEVC/source/Lib/TLibEncoder/TEncSearch.cpp:2206:79: error: array subscript has type ?char? [-Werror=char-subscripts]
         x265::pixelcmp sa8d = x265::primitives.sa8d[g_aucConvertToBit[uiWidth]];
                                                                               ^